volumes:
  ollama: {}
  snapshots: {}

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    command: serve
  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - snapshots:/snapshots
    ports:
      - 6333:6333
  flask:
        build: .
        container_name: lawpaw_backend
        ports:
            - "5000:5000"
        volumes:
            - .:/backend
        depends_on:
            - qdrant
            - ollama
            
            